### ISSUE TITLE
Incompatible with `pandoc`?

### ISSUE THREAD

**Issue by stefanocoretta** [driusan/lmt#4]
The latest commit 460b02b moves the file name and the chunk name specifications after the opening three backticks. Unfortunately this seems not to be compatible with `pandoc` markdown, while of course it is with GitHub markdown.

This means that if we want to compile documentation using `pandoc` to convert from an `.md` file to, say, a `.pdf` (rather than using a GitHub markdown compatible renderer), the resulting file does not correctly creates chunks because the `lmt` file names and chunk names interfere (I even tried converting from GitHub flavoured markdown to Pandoc's markdown but it does not work).

**Comment by driusan** [comment]
This is a bit tricky since code blocks aren't very well standardized across markdown variants. The [pandoc documentation](http://pandoc.org/MANUAL.html#markdown-variants) says it has GitHub flavored markdown support with `-f gfm`, have you tried that? If that doesn't work, is it feasible to fix it on the pandoc side?

If not, you could locally revert the commit until we have a more robust solution.

**Comment by stefanocoretta** [comment]
I tried with `-f gfm` but it does not work (probably the definitions of `gfm` is not up to date with the one used on GitHub?). Yes, probably it makes more sense checking this with `pandoc`, I might do that soon.

For now reverting to previous commit will do! Thanks. I will close this for now.

**Comment by stefanocoretta** [comment]
Just FYI, I don't know if I was doing something wrong, but now using Pandoc 2.4 and `-f gfm` the output pdf looks fine. Plus, on an unrelated note, the new option `--syntax-definition` allows for dynamically loading new languages highlighting. So I'd say `lmt` and `pandoc` work perfectly together. One tangles the code and the other weaves the documentation! 🤓
